version: "3"
services:
  game-website:
    hostname: antarace
    build: .
    container_name: antarace-website
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - game-postgres
    networks:
      - game-network

  game-postgres:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: antarace
    ports:
      - "5432:5432"

networks:
  game-network: